#!/bin/bash

if [ ! -f ${HOME}/.gitconfig.local ]; then
  # Okay, this doesn't really work with rcm at the moment, but we'll leave it be
  # read -p "Name [Tom Hoover]: " USERNAME
  # read -p "Email [my gmail]: " EMAIL

  USERNAME=${USERNAME:-Tom Hoover}
  # Silly encoding so my email isn't scraped as easily
  DEFAULT=$(echo Z3ViYmlyZUB0em52eS5wYnoK | base64 --decode | tr 'A-Za-z' 'N-ZA-Mn-za-m')
  EMAIL=${EMAIL:-$DEFAULT}
  EDITOR=${EDITOR:-vim}
  cat ../gitconfig.local.template  | EMAIL=${EMAIL} USERNAME=${USERNAME} envsubst > ${HOME}/.gitconfig.local
fi

if [ ! -d ${HOME}/.config/nvim/pack/minpac/opt/minpac ]; then
  git clone -q https://github.com/k-takata/minpac.git ${HOME}/.config/nvim/pack/minpac/opt/minpac
fi

nvim -u ${HOME}/.config/nvim/plugins.vim --headless "+packadd minpac" "+call minpac#update('', {'do': 'quitall'})"

# Silence output since I don't care if we don't re-write the standard tags. I could specify the minpac directory
# directly, but I might switch package managers in the future.
nvim -u NONE --headless "+helptags ALL" "+quit" 2> /dev/null

export PYTHONWARNINGS="ignore:DEPRECATION"
# We're going to default to Python 3 now
pip3 install --user -q --upgrade --no-warn-script-location --requirement=../requirements.txt
